//This is AUTOGENERATED FILE by bb-assets-generator-plugin. DO NOT EDIT!!!

export const assets_ts = "../assets/assets.ts";
export const img = {
    bobril_png: "../assets/img/bobril.png",
    bobrilInverse_png: "../assets/img/bobrilInverse.png",
};
